on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.3.Rel1'

    - name: Install Python dependencies
      run: python3 -m pip install --upgrade pip crcmod

    - name: Checkout
      uses: actions/checkout@v3

    - name: Submodules
      run: git submodule update --init --recursive --depth 1

    - name: Make
      run:  make

    - name: size
      run:  arm-none-eabi-size firmware

    - name: rename
      run: mv bin/firmware.bin k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.raw.bin

    - name: rename
      run: mv bin/firmware.packed.bin k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.bin

    - name: rename
      run: mv chirp/chirp_uvk5_fagci_reborn.py k5-fagci-r3b0rn-${{ github.event.release.tag_name }}-chirp-module.py

    - name: 'Add unpacked FW to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.raw.bin

    - name: 'Add packed FW to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.bin

    - name: 'Add chirp module to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}-chirp-module.py

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      if: 'github.event.release.prerelease'
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.bin
        message: |
          ${{ github.event.release.name }}

          ${{ github.event.release.body }}

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      if: 'github.event.release.prerelease'
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}-chirp-module.py
        message: " "
          
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      if: '!github.event.release.prerelease'
      with:
        to: ${{ secrets.TELEGRAM_TO_RELEASE }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}.bin
        message: |
          ${{ github.event.release.name }}

          ${{ github.event.release.body }}

    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      if: '!github.event.release.prerelease'
      with:
        to: ${{ secrets.TELEGRAM_TO_RELEASE }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: k5-fagci-r3b0rn-${{ github.event.release.tag_name }}-chirp-module.py
        message: " "
